steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west1-docker.pkg.dev/qwiklabs-gcp-03-3f208bb2c41f/bert-sentiment-classifier/bert-sentiment-classifier:latest', '.' ]
images: 
- 'us-west1-docker.pkg.dev/qwiklabs-gcp-03-3f208bb2c41f/bert-sentiment-classifier/bert-sentiment-classifier:latest'